-- Common lab setup code
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS TECHUP25;
CREATE WAREHOUSE IF NOT EXISTS TECHUP25_WH;
CREATE ROLE TECHUP25_RL;

-- TODO: Add pypi EAI

CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TECHUP25_RL;
GRANT APPLICATION ROLE snowflake.cortex_analyst_requests_admin TO ROLE TECHUP25_RL;
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE TECHUP25_RL;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE TECHUP25_RL;
GRANT USAGE, CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE TECHUP25_RL;
GRANT ALL ON DATABASE TECHUP25 TO ROLE TECHUP25_RL;
GRANT ALL ON WAREHOUSE TECHUP25_WH TO ROLE TECHUP25_RL;
GRANT ROLE TECHUP25_RL TO ROLE ACCOUNTADMIN;
SET current_user_name = CURRENT_USER();
GRANT ROLE TECHUP TO USER IDENTIFIER($current_user_name);

-- Lab specific Accountadmin
CREATE OR REPLACE API INTEGRATION TECHUP_GIT_INT
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-snasim')
    ENABLED = TRUE;
GRANT USAGE ON INTEGRATION TECHUP_GIT_INT TO ROLE TECHUP25_RL;

-- Lab specific
USE ROLE TECHUP25_RL;
CREATE SCHEMA IF NOT EXISTS MULTIMODAL_RAG;
CREATE OR REPLACE GIT REPOSITORY TECHUP_MULTIMODAL_RAG
    API_INTEGRATION = TECHUP_GIT_INT
    ORIGIN = 'https://github.com/sfc-gh-snasim/Multimodal_RAG.git';

-- TODO CREATE STREAMLIT APP, NOTEBOOK