-- Common lab setup code
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS TECHUP25;
CREATE WAREHOUSE IF NOT EXISTS TECHUP25_WH;
CREATE ROLE TECHUP25_RL;

CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TECHUP25_RL;
GRANT APPLICATION ROLE snowflake.cortex_analyst_requests_admin TO ROLE TECHUP25_RL;
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE TECHUP25_RL;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE TECHUP25_RL;
GRANT USAGE, CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE TECHUP25_RL;
GRANT ALL ON DATABASE TECHUP25 TO ROLE TECHUP25_RL;
GRANT ALL ON WAREHOUSE TECHUP25_WH TO ROLE TECHUP25_RL;
GRANT ROLE TECHUP25_RL TO ROLE ACCOUNTADMIN;

SET current_user_name = CURRENT_USER();

GRANT ROLE TECHUP25_RL TO USER IDENTIFIER($current_user_name);

-- Lab specific setup - use Accountadmin
CREATE OR REPLACE API INTEGRATION TECHUP_GIT_INT
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-snasim')
    -- ALLOWED_AUTHENTICATION_SECRETS = (sheena_git)
    ENABLED = TRUE;
GRANT USAGE ON INTEGRATION TECHUP_GIT_INT TO ROLE TECHUP25_RL;

-- TODO: Add pypi EAI

CREATE COMPUTE POOL TECHUP_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS;

GRANT USAGE, OPERATE ON COMPUTE POOL TECHUP_COMPUTE_POOL TO ROLE TECHUP25_RL;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'All';

-- Lab specific - use role TECHUP25_RL
USE ROLE TECHUP25_RL;
CREATE SCHEMA IF NOT EXISTS MULTIMODAL_RAG;
CREATE OR REPLACE GIT REPOSITORY TECHUP_MULTIMODAL_RAG
    API_INTEGRATION = TECHUP_GIT_INT
    -- GIT_CREDENTIALS = sheena_git
    ORIGIN = 'https://github.com/sfc-gh-snasim/Multimodal_RAG.git';

CREATE OR REPLACE NOTEBOOK TECHUP25.MULTIMODAL_RAG.CortexMultimodalSearch
    FROM '@TECHUP25.MULTIMODAL_RAG.TECHUP_MULTIMODAL_RAG/branches/main/' 
        MAIN_FILE = 'cortex_search_multimodal.ipynb' 
        QUERY_WAREHOUSE = TECHUP25_WH; 

CREATE OR REPLACE STREAMLIT TECHUP25.MULTIMODAL_RAG.CortexMultimodalSearchApp -- TODO: this errors since imports were added
  FROM '@TECHUP25.MULTIMODAL_RAG.TECHUP_MULTIMODAL_RAG/branches/main/' 
  MAIN_FILE = 'streamlit_chatbot_multimodal_rag.py'
--   IMPORTS = ('@TECHUP25.MULTIMODAL_RAG.TECHUP_MULTIMODAL_RAG/branches/main/streamlit.txt')
  TITLE = 'Cortex Multimodal Search 🔎'
  QUERY_WAREHOUSE = TECHUP25_WH;