-- Common lab setup code
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS TECHUP25;
CREATE SCHEMA IF NOT EXISTS TECHUP25.MULTIMODAL_RAG;
CREATE WAREHOUSE IF NOT EXISTS TECHUP25_WH;
CREATE ROLE IF NOT EXISTS TECHUP25_RL;

CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TECHUP25_RL;
GRANT APPLICATION ROLE snowflake.cortex_analyst_requests_admin TO ROLE TECHUP25_RL;
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE TECHUP25_RL;
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE TECHUP25_RL;
GRANT USAGE, CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE TECHUP25_RL;
GRANT ALL ON DATABASE TECHUP25 TO ROLE TECHUP25_RL;
GRANT ALL ON SCHEMA TECHUP25.MULTIMODAL_RAG TO ROLE TECHUP25_RL;
GRANT ALL ON WAREHOUSE TECHUP25_WH TO ROLE TECHUP25_RL;
GRANT ROLE TECHUP25_RL TO ROLE ACCOUNTADMIN;

SET current_user_name = CURRENT_USER();
GRANT ROLE TECHUP25_RL TO USER IDENTIFIER($current_user_name);

-- Lab specific setup - use Accountadmin
USE DATABASE TECHUP25;
USE SCHEMA MULTIMODAL_RAG;

CREATE OR REPLACE API INTEGRATION TECHUP_GIT_INT
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-snasim')
    -- ALLOWED_AUTHENTICATION_SECRETS = (sf_git_token)
    ENABLED = TRUE;

GRANT USAGE ON INTEGRATION TECHUP_GIT_INT TO ROLE TECHUP25_RL;

-- Add pypi and s3 External Access integration 
CREATE OR REPLACE NETWORK RULE TECHUP_PYPI_NETWORK_RULE MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = (
  'pypi.org',
  'pypi.python.org',
  'pythonhosted.org',
  'files.pythonhosted.org',
  'sheena-tko25-multimodal-rag.s3.amazonaws.com'
);

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION TECHUP_PYPI_ACCESS_INTEGRATION
ALLOWED_NETWORK_RULES = (TECHUP_PYPI_NETWORK_RULE)
ENABLED = true;
GRANT USAGE ON INTEGRATION TECHUP_PYPI_ACCESS_INTEGRATION TO ROLE TECHUP25_RL;

-- Create compute to run notebooks
CREATE COMPUTE POOL IF NOT EXISTS TECHUP_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS;
GRANT USAGE, OPERATE ON COMPUTE POOL TECHUP_COMPUTE_POOL TO ROLE TECHUP25_RL;

-- Set cross region to AWS US for availability of functions for HOL
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';

-- Create an external stage to copy raw input data files 
-- Files are also available at https://drive.google.com/drive/folders/1bExhPiJlF9aNushnXeLLBR4m9EMaShHw?usp=sharing
-- Directly download and upload into  internal stage RAW_DOCS_INTERNAL in case of any errors in creating external stage.
CREATE OR REPLACE STAGE TECHUP25.MULTIMODAL_RAG.RAW_DOCS
URL='s3://sheena-tko25-multimodal-rag/'
CREDENTIALS=(AWS_KEY_ID='AKIAXBUYSSFIMDJGVNXL' AWS_SECRET_KEY='zaQQWmgMKa9tMGcjO4HcdMsKn5bJ/FaOhMvL8nut') -- Key only have restricted access to raw_data pdf
ENCRYPTION=(TYPE='AWS_SSE_KMS' KMS_KEY_ID = 'aws/key');

-- Create an internal stage and copy all files to internal stage (Some functions in this HOL only works on internal stage files)
CREATE OR REPLACE STAGE TECHUP25.MULTIMODAL_RAG.RAW_DOCS_INTERNAL DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
COPY FILES INTO @TECHUP25.MULTIMODAL_RAG.RAW_DOCS_INTERNAL/raw_pdf/
FROM @TECHUP25.MULTIMODAL_RAG.RAW_DOCS/raw_data/;

-- Lab specific - use role TECHUP25_RL
USE ROLE TECHUP25_RL;

-- Create a Git integration to copy the whole code from repository  
CREATE OR REPLACE GIT REPOSITORY  TECHUP25.MULTIMODAL_RAG.TECHUP_MULTIMODAL_RAG
    API_INTEGRATION = TECHUP_GIT_INT
    -- GIT_CREDENTIALS = SF_GIT_TOKEN
    ORIGIN = 'https://github.com/sfc-gh-snasim/Multimodal_RAG.git';

CREATE OR REPLACE NOTEBOOK TECHUP25.MULTIMODAL_RAG.CortexMultimodalSearch
    FROM '@TECHUP25.MULTIMODAL_RAG.TECHUP_MULTIMODAL_RAG/branches/main/' 
        MAIN_FILE = 'cortex_search_multimodal.ipynb'
        RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME'
        COMPUTE_POOL = TECHUP_COMPUTE_POOL
        QUERY_WAREHOUSE = TECHUP25_WH
        EXTERNAL_ACCESS_INTEGRATIONS = (TECHUP_PYPI_ACCESS_INTEGRATION); 

CREATE OR REPLACE STREAMLIT TECHUP25.MULTIMODAL_RAG.CortexMultimodalSearchApp
  FROM '@TECHUP25.MULTIMODAL_RAG.TECHUP_MULTIMODAL_RAG/branches/main/' 
  MAIN_FILE = 'streamlit_chatbot_multimodal_rag.py'
  TITLE = 'Cortex Multimodal Search 🔎'
  QUERY_WAREHOUSE = TECHUP25_WH;